# Generated by Django 5.2.10 on 2026-01-07 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Application Number')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('address', models.TextField(verbose_name='Address')),
                ('credit_card_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Credit Card Limit')),
                ('current_debt', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Current Debt Amount')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank Name')),
                ('card_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Card Type')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_credit_debts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_debt_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Card Debt Application',
                'verbose_name_plural': 'Credit Card Debt Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Application Number')),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan')], max_length=20, verbose_name='Loan Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Loan Amount')),
                ('credit_score_range', models.CharField(choices=[('excellent', 'Excellent (750+)'), ('good', 'Good (700-749)'), ('fair', 'Fair (650-699)'), ('poor', 'Poor (Below 650)')], max_length=20, verbose_name='Credit Score Range')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('address', models.TextField(verbose_name='Address')),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Annual Income')),
                ('monthly_rent_mortgage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Rent/Mortgage')),
                ('employment_status', models.CharField(max_length=50, verbose_name='Employment Status')),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Employer Name')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Name')),
                ('business_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Business Type')),
                ('business_address', models.TextField(blank=True, null=True, verbose_name='Business Address')),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Annual Revenue')),
                ('years_in_business', models.IntegerField(blank=True, null=True, verbose_name='Years in Business')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Application Number')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('address', models.TextField(verbose_name='Address')),
                ('ssn_last_four', models.CharField(max_length=4, verbose_name='SSN Last 4 Digits')),
                ('filing_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('both', 'Both')], max_length=20, verbose_name='Filing Type')),
                ('tax_year', models.IntegerField(verbose_name='Tax Year')),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('student', 'Student')], max_length=20, verbose_name='Employment Status')),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Annual Income')),
                ('expected_refund', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Expected Refund')),
                ('actual_refund', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Actual Refund')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Name')),
                ('business_ein', models.CharField(blank=True, max_length=20, null=True, verbose_name='Business EIN')),
                ('business_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Business Revenue')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('documents_required', 'Documents Required'), ('in_progress', 'In Progress'), ('filed', 'Filed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('documents', models.JSONField(blank=True, default=list, verbose_name='Uploaded Documents')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tax_refunds', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_refund_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Refund Application',
                'verbose_name_plural': 'Tax Refund Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Withdrawal Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Withdrawal Amount')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank Name')),
                ('account_holder_name', models.CharField(max_length=255, verbose_name='Account Holder Name')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('routing_number', models.CharField(max_length=20, verbose_name='Routing Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='financial.loanapplication')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'ordering': ['-created_at'],
            },
        ),
    ]
