# Generated by Django 5.2.10 on 2026-01-07 21:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('role', models.CharField(choices=[('applicant', 'Applicant'), ('employer', 'Employer'), ('admin', 'Admin')], default='applicant', max_length=20, verbose_name='Role')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('headline', models.CharField(blank=True, max_length=255, null=True, verbose_name='Professional Headline')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio/Summary')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile')),
                ('open_to_work', models.BooleanField(default=False, verbose_name='Open to Work')),
                ('desired_salary_min', models.IntegerField(blank=True, null=True, verbose_name='Desired Salary Min')),
                ('desired_salary_max', models.IntegerField(blank=True, null=True, verbose_name='Desired Salary Max')),
                ('desired_job_types', models.JSONField(blank=True, default=list, verbose_name='Desired Job Types')),
                ('desired_locations', models.JSONField(blank=True, default=list, verbose_name='Desired Locations')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Certification Name')),
                ('issuing_organization', models.CharField(max_length=255, verbose_name='Issuing Organization')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Credential ID')),
                ('credential_url', models.URLField(blank=True, null=True, verbose_name='Credential URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255, verbose_name='Institution')),
                ('degree', models.CharField(choices=[('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=50, verbose_name='Degree Type')),
                ('field_of_study', models.CharField(max_length=255, verbose_name='Field of Study')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='GPA')),
                ('honors', models.CharField(blank=True, max_length=255, null=True, verbose_name='Honors')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, verbose_name='Currently Working Here')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('achievements', models.JSONField(blank=True, default=list, verbose_name='Achievements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Skill Name')),
                ('skill_type', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skill')], default='technical', max_length=20, verbose_name='Skill Type')),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20, verbose_name='Proficiency')),
                ('years_of_experience', models.IntegerField(blank=True, null=True, verbose_name='Years of Experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
