# Generated by Django 5.2.10 on 2026-01-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Private notes visible only to admins",
                null=True,
                verbose_name="Admin Notes",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Premium/featured user status",
                verbose_name="Featured User",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_suspended",
            field=models.BooleanField(
                default=False,
                help_text="Temporarily suspended account",
                verbose_name="Suspended",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Verified badge for trusted users",
                verbose_name="Verified User",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Last Login IP"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="suspend_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Suspension Reason"
            ),
        ),
    ]
