# Generated by Django 5.2.10 on 2026-01-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_conversation_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
